// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPXxczqXRo_7ZbmVFOFAk2N1l-j2YWOUQ',
    appId: '1:1030800366302:android:21a9e330a52d1df8eac04f',
    messagingSenderId: '1030800366302',
    projectId: 'ligdoctor-app',
    databaseURL: 'https://ligdoctor-app.firebaseio.com',
    storageBucket: 'ligdoctor-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzH37_M-4esIrAe6c3fBSfmSnzOwsb7A',
    appId: '1:1030800366302:ios:696f9ba7a31d313deac04f',
    messagingSenderId: '1030800366302',
    projectId: 'ligdoctor-app',
    databaseURL: 'https://ligdoctor-app.firebaseio.com',
    storageBucket: 'ligdoctor-app.appspot.com',
    androidClientId: '1030800366302-314jk3s3u3ce6ptkc5cfl3ne32detsg8.apps.googleusercontent.com',
    iosClientId: '1030800366302-u8e3pctgrgatlb1oh8i67rsl396lu901.apps.googleusercontent.com',
    iosBundleId: 'br.com.ligdoctor.profissionais',
  );
}
